services:
  mongo:
    image: 'mongo:latest'
    container_name: hiraeth-mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  java:
    build: ./
    container_name: hiraeth-java
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_SEND_DEFAULT_PII=${SENTRY_SEND_DEFAULT_PII}
      - SENTRY_LOGS_ENABLED=${SENTRY_LOGS_ENABLED}
    depends_on:
      - mongo
    networks:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
